backend:
  name: git-gateway
  branch: main
  base_url: https://amazing-monstera-dd2338.netlify.app # URL da sua Netlify

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "artigos"
    label: "Novos Artigos"
    folder: "content/artigos"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Autor", name: "author", widget: "string", default: "Dr. Bruno Faustino" }
      - { label: "Texto Completo", name: "body", widget: "markdown" }
      - { label: "Referência Bibliográfica", name: "reference", widget: "text", required: false }
      - { label: "Data", name: "date", widget: "datetime" }
